// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNj8p16aJ4iYVYrRsdn4OMoH5coclrP90',
    appId: '1:21523245785:web:ddc34cc901f3af1d7aecc8',
    messagingSenderId: '21523245785',
    projectId: 'flutter-ecommerce-6a614',
    authDomain: 'flutter-ecommerce-6a614.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-6a614.appspot.com',
    measurementId: 'G-YBEPQMH19M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZfarOWvGjinBxp_bzF8bXG-A9co3EY9U',
    appId: '1:21523245785:android:68d6689885802f477aecc8',
    messagingSenderId: '21523245785',
    projectId: 'flutter-ecommerce-6a614',
    storageBucket: 'flutter-ecommerce-6a614.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgY6gs1twcI3QXzoqskD3e9CbfuwbDwrE',
    appId: '1:21523245785:ios:f4acfa90354522f27aecc8',
    messagingSenderId: '21523245785',
    projectId: 'flutter-ecommerce-6a614',
    storageBucket: 'flutter-ecommerce-6a614.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgY6gs1twcI3QXzoqskD3e9CbfuwbDwrE',
    appId: '1:21523245785:ios:f4acfa90354522f27aecc8',
    messagingSenderId: '21523245785',
    projectId: 'flutter-ecommerce-6a614',
    storageBucket: 'flutter-ecommerce-6a614.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNj8p16aJ4iYVYrRsdn4OMoH5coclrP90',
    appId: '1:21523245785:web:9aac92df3626ed807aecc8',
    messagingSenderId: '21523245785',
    projectId: 'flutter-ecommerce-6a614',
    authDomain: 'flutter-ecommerce-6a614.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-6a614.appspot.com',
    measurementId: 'G-4QYK2ZR3QP',
  );
}
